#Requires AutoHotkey v2.0

; Source of truth for every hotkey + toggle. Layout: each entry sets `tab`,
; `row` (0..N), `col` (0|1|2); `gap:true` inserts a row break.
; Field reference: section (Hotkey | Toggle | unset for pixel-only),
; canBeDisabled, pixelSelect, vars (multi-pixel), textField, regexpField,
; labelField, gameScoped (per PoE1/PoE2/LE), game,
; toggleOnInstance (dynamic — only safe zones),
; globalScope (hotkey fires outside the game window),
; companionKey (Toggle: extra hotkey to register while enabled).

global Configs := Map(
  ; ============================ General ============================
  "Settings", HotkeyEntry({
    name: "Settings (This GUI)",
    func: Settings.Open,
    defaultHotkey: "F10",
    canBeDisabled: false,
    tab: "General",
    row: 0,
    col: 0,
    tooltip: "Open this Settings window.",
  }),
  "KillSwitch", HotkeyEntry({
    name: "Kill Switch",
    func: KillSwitch,
    defaultHotkey: "Home",
    canBeDisabled: false,
    globalScope: true,
    tab: "General",
    row: 0,
    col: 1,
    tooltip: "Quit the app. Works even when the game isn't focused.",
  }),
  "ForceLogout", HotkeyEntry({
    name: "Force Logout",
    func: Logout.Force,
    tab: "General",
    row: 0,
    col: 2,
    tooltip: "Kill the server connection. Escape imminent death.",
  }),
  "ToggleHotkeys", HotkeyEntry({
    name: "Master Hotkey`n(toggle other hotkeys)",
    func: Keybinds.Toggle,
    canBeDisabled: false,
    tab: "General",
    row: 1,
    col: 0,
    gap: true,
    tooltip: "Turn every other hotkey off. Press again to re-enable.",
  }),
  "ToggleOverlayPosition", {
    name: "Toggle Overlay Position",
    pixelSelect: true,
    tab: "General",
    row: 2,
    col: 0,
    gap: true,
    tooltip: "Where the CTRL / SHIFT overlay appears on screen.",
    pixelTooltips: Map(
      "ToggleOverlayPosition", "Click where you want the overlay to appear on screen.",
    ),
  },
  "ToggleCtrl", ToggleEntry({
    name: "Toggle CTRL",
    func: Modifiers.ToggleCtrl,
    companionKey: "*Ctrl",
    tab: "General",
    row: 2,
    col: 1,
    gap: true,
    tooltip: "Press CTRL once to hold it, again to release.",
  }),
  "ToggleShift", ToggleEntry({
    name: "Toggle SHIFT",
    func: Modifiers.ToggleShift,
    companionKey: "*Shift",
    tab: "General",
    row: 2,
    col: 2,
    gap: true,
    tooltip: "Press SHIFT once to hold it, again to release.",
  }),
  "CtrlClickSpamToggle", HotkeyEntry({
    name: "Spam Ctrl Click",
    func: ClickSpam.Toggle,
    tab: "General",
    row: 3,
    col: 0,
    gap: true,
    tooltip: "Hold Ctrl + spam left-click. Press again to stop.",
  }),
  "ToggleCtrlKeybind", HotkeyEntry({
    name: "Alternative CTRL keybind",
    func: Modifiers.ToggleCtrl,
    tab: "General",
    row: 3,
    col: 1,
    gap: true,
    tooltip: "Alternate keybind for Toggle CTRL.",
  }),
  "ToggleShiftKeybind", HotkeyEntry({
    name: "Alternative SHIFT keybind",
    func: Modifiers.ToggleShift,
    tab: "General",
    row: 3,
    col: 2,
    gap: true,
    tooltip: "Alternate keybind for Toggle SHIFT.",
  }),
  ; ============================ PoE Commands ============================
  "ChatCommand1", ChatCommandConfig(1, "F5", "/hideout"),
  "ChatCommand2", ChatCommandConfig(2, "F6", "/kingsmarch"),
  "ChatCommand3", ChatCommandConfig(3, "F7", "/monastery"),
  "ChatCommand4", ChatCommandConfig(4, "", ""),
  "ChatCommand5", ChatCommandConfig(5, "", ""),
  "ChatCommand6", ChatCommandConfig(6, "", ""),
  ; ============================ PoE Crafting ============================
  "CraftingCurrency1", CurrencyConfig(1, 0, 0),
  "CraftingCurrency2", CurrencyConfig(2, 0, 1),
  "CraftingCurrency3", CurrencyConfig(3, 0, 2),
  "CraftingCurrency4", CurrencyConfig(4, 1, 0, true),
  "CraftingCurrency5", CurrencyConfig(5, 1, 1, true),
  "CraftingCurrency6", CurrencyConfig(6, 1, 2, true),
  "CalcWeaponDPS", HotkeyEntry({
    name: "Calc. Weapon DPS",
    func: WeaponDPS.Show,
    game: "PathOfExile",
    tab: "PoE Crafting",
    row: 2,
    col: 0,
    gap: true,
    tooltip: "Hover a weapon to see its DPS breakdown.",
  }),
  ; ============================ PoE Inventory ============================
  "DropItem", HotkeyEntry({
    name: "Drop Item From Inventory",
    func: DropItem,
    game: "PathOfExile",
    tab: "PoE Inventory",
    row: 0,
    col: 0,
    tooltip: "Hover an item to drop it on the ground. Only works in loot areas.",
  }),
  "OpenStackedDivinationDeck", HotkeyEntry({
    name: "Open Stacked Divination Deck",
    func: OpenStackedDivinationDeck,
    game: "PathOfExile",
    tab: "PoE Inventory",
    row: 0,
    col: 1,
    tooltip: "Hover a stacked deck to drop one card. Outdoors only.",
  }),
  "TradeDivinationCard", HotkeyEntry({
    name: "Trade Divination Card",
    func: PerformDivinationTrading,
    game: "PathOfExile",
    tab: "PoE Inventory",
    row: 0,
    col: 2,
    pixelSelect: true,
    vars: ["TradeDivinationCardButton", "TradeDivinationCardItemArea"],
    tooltip: "Open the trade screen and hover a stack to trade it.",
    pixelTooltips: Map(
      "TradeDivinationCardButton", "Click the Accept / Trade button in the trade window.",
      "TradeDivinationCardItemArea", "Click the item slot where the card is placed.",
    ),
  }),
  "FillShipment", HotkeyEntry({
    name: "Fill Shipments",
    func: Shipments.Fill,
    game: "PathOfExile",
    tab: "PoE Inventory",
    row: 1,
    col: 0,
    gap: true,
    tooltip: "Click the first shipment cell, then press to fill every row.",
  }),
  ; Full-row (span:3) RegExp search slots; per-PoE-variant patterns.
  "HighlightShopItems1", RegexpEntry(1, "F1",
    "(\w\W){5}|-\w-.-|(-\w){4}|(-\w){5}|nne|rint|ll g", 0, false),
  "HighlightShopItems2", RegexpEntry(2, "", "", 1, false),
  "HighlightShopItems3", RegexpEntry(3, "", "", 2, false),
  ; ============================ Last Epoch ============================
  "TransferMaterialsWInventory", TransferConfig(
    "Transfer Materials (w/ inventory open)", "TransferMaterialsWInventory", false, 0, 0,
    "Clicks the configured pixel with your inventory already open."
  ),
  "TransferMaterialsWOInventory", TransferConfig(
    "Transfer Materials (w/o inventory open)", "TransferMaterialsWOInventory", true, 0, 1,
    "Opens your inventory, clicks the pixel, then closes the inventory."
  ),
  "ShatterItem", HotkeyEntry({
    name: "Shatter Item",
    func: ShatterItem,
    game: "LastEpoch",
    tab: "Last Epoch",
    row: 0,
    col: 2,
    pixelSelect: true,
    vars: ["ShatterItemRuneSelection", "ShatterItemShatterRune", "ShatterItemButton"],
    tooltip: "Hover an item to shatter it.",
    pixelTooltips: Map(
      "ShatterItemRuneSelection", "Click the rune selection box.",
      "ShatterItemShatterRune", "Click the Shatter rune.",
      "ShatterItemButton", "Click the Shatter button.",
    ),
  }),
)